---
development:
  cloud_name: devsincmail
  api_key: '193497724595657'
  api_secret: arexN335wLLW1nT2LIhszBx-b20
  enhance_image_tag: true
  static_file_support: false
  

production:
  cloud_name: devsincmail
  api_key: '193497724595657'
  api_secret: arexN335wLLW1nT2LIhszBx-b20
  enhance_image_tag: true
  static_file_support: true

test:
  cloud_name: devsincmail
  api_key: '193497724595657'
  api_secret: arexN335wLLW1nT2LIhszBx-b20
  enhance_image_tag: true
  static_file_support: false
